# Generated by Django 4.2.5 on 2023-10-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_attendance_date_alter_attendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='AdmissionYear',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='Parentname',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='Parentphonenumber',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
